### ISSUE TITLE
Not able to run Quantifly with these images?

### ISSUE THREAD

**Issue by ghost** [dwaithe/quantifly#1]
Hi Dominic Waithe,

I've recently tried to use your program but the images below, but found that the program would become unresponsive. I've scanned these images as .tiff files and have even tried to cut them up into small images to use. The images were scanned at approximately 1200 dpi. Do you think it would be an issue with the images and do you think it would be possible to modify the code to be able to use these images?

The original image:
https://www.dropbox.com/s/l2shpn1i2j2iczm/Test%202.tif?dl=0

![Test Image 2-1](https://cloud.githubusercontent.com/assets/2957892/10261274/8370110c-6944-11e5-8a3f-110ff93897de.png)
![Test Image 2-2](https://cloud.githubusercontent.com/assets/2957892/10261275/83711408-6944-11e5-904f-f27ad123d626.png)
![Test Image 2-3](https://cloud.githubusercontent.com/assets/2957892/10261276/83726d62-6944-11e5-9967-51796f950a87.png)
![Test Image 2-4](https://cloud.githubusercontent.com/assets/2957892/10261277/83733b0c-6944-11e5-9c5e-c6c68f03c215.png)

**Comment by dwaithe** [comment]
Hi,
Thanks for your message. I have taken a look at your images. They are fine in theory but the resolution is a bit high for the software. You want to aim to have images which are around 400 x 400 pixels in size. If you create them this size there should be more than enough resolution for the analysis you require.  I also had a look at the very large image grid that you supplied.  I was very interested by this grid and I came up with a way in which you can use this more or less directly. This will saving you having to carve it up manually and should speed your analysis dramatically

To use the grid image I recommend installing and using Fiji software. We will use this software to first process the images into a stack of image regions. 
http://fiji.sc/Downloads.
To do this, you will also need a macro which I have written  which converts the image grid into individual images:
https://github.com/dwaithe/quantifly/blob/master/grid_to_stack.ijm

Next run Fiji. Open your image (the large 500+ MB) grid image. Next open the macro grid_to_stack.ijm. The best way to do this is just to drag the macro file to the toolbar and it should open in the Fiji script editor. Click the macro 'Run' button at the bottom of the script editor. Wait for the macro to finish and you should have an image stack of your isolated drosophila regions. These regions are assembled from left-to-right row-by-row from top to bottom of your grid image. Once processed, save the image stack as a .tiff (File->Save As-> Tiff).

The images are now ready to be processed using QuantiFly software. Load in the tiff stack, when using the training software, just load a small number of the images from the stack (e.g. <8). Train the software by drawing rectangular regions and clicking the eggs within. I used an 'Input Sigma for kernel size' or 1.5 rather than 1.0 (just because the eggs are quite large). Once you have provided a number of training examples like in the attached image. Click 'Train' and then review the performance. Keep annotating regions until the performance is accurate.
<img width="1257" alt="screen shot 2015-10-05 at 21 32 53" src="https://cloud.githubusercontent.com/assets/4719022/10292710/abc9ab70-6ba8-11e5-931d-4498a1f743d4.png">
If you need help with this check the manual or just say and I can provide you with a video or something using your data. Provide training examples from dense egg regions, sparse egg regions and areas of background. The more the better. Once you have trained your model, make sure to save it. Open the same data and any other files you have processed into stacks in the batch mode software. Evaluate the images with your model. If your model is well trained you should generate images like those attached to this message. You have access to all the counts in a spread-sheet by clicking 'Save Output Data' button.

Good luck!. If you take the time to train a good model you can evaluate many many images very quickly. Your grids look like a great way to run many experiments in parallel. If you like the method I have provided I can perhaps develop the quantifly software to recognise the images directly to speed up your processing. If you are an academic I would prefer to work with you directly to achieve this, if you are a company we can arrange somekind of consultancy if you are interested.

If you have any more questions, please let me know.
Best,
Dominic

<img width="873" alt="screen shot 2015-10-05 at 21 06 29" src="https://cloud.githubusercontent.com/assets/4719022/10292775/0b22d736-6ba9-11e5-866e-2ca45feb03cc.png">
